name: image_cropper_for_web
version: 3.0.0+stub
description: Temporary web stub for image_cropper to avoid Flutter web build issues.
homepage: https://github.com/umityeke/cringe-bankasi
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  image_cropper_platform_interface: ^5.0.0

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  plugin:
    implements: image_cropper
    platforms:
      web:
        pluginClass: ImageCropperForWeb
        fileName: image_cropper_for_web.dart
