version: "3.8"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: cringebank-mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${CRINGEBANK_MSSQL_SA_PASSWORD:?missing env CRINGEBANK_MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  mssql_data:
