// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQWl1VSXesJlEdu04JsRWzleql-TEGke0',
    appId: '1:127594268731:web:0e80e1a01665d3d7e8b41e',
    messagingSenderId: '127594268731',
    projectId: 'cringebank',
    authDomain: 'cringebank.firebaseapp.com',
    storageBucket: 'cringebank.firebasestorage.app',
    measurementId: 'G-ZZ57ZVGP3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ3x_nXxrzjTGyAytVsJwAZ2ebpIzb31Q',
    appId: '1:127594268731:android:229855fd3c141f43e8b41e',
    messagingSenderId: '127594268731',
    projectId: 'cringebank',
    storageBucket: 'cringebank.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2SmlFyvetrOjWfSiKKIHYYpaK4W8N2pU',
    appId: '1:127594268731:ios:e3f4dd2f21238c71e8b41e',
    messagingSenderId: '127594268731',
    projectId: 'cringebank',
    storageBucket: 'cringebank.firebasestorage.app',
    iosBundleId: 'com.example.cringeBankasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2SmlFyvetrOjWfSiKKIHYYpaK4W8N2pU',
    appId: '1:127594268731:ios:e3f4dd2f21238c71e8b41e',
    messagingSenderId: '127594268731',
    projectId: 'cringebank',
    storageBucket: 'cringebank.firebasestorage.app',
    iosBundleId: 'com.example.cringeBankasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQWl1VSXesJlEdu04JsRWzleql-TEGke0',
    appId: '1:127594268731:web:0e80e1a01665d3d7e8b41e',
    messagingSenderId: '127594268731',
    projectId: 'cringebank',
    authDomain: 'cringebank.firebaseapp.com',
    storageBucket: 'cringebank.firebasestorage.app',
    measurementId: 'G-ZZ57ZVGP3D',
  );

}