// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLd4GiCnyk-1UfFF8hKUSc0prNQ5ERWoM',
    appId: '1:688167942712:web:8947c9f0c89844aea5c4cd',
    messagingSenderId: '688167942712',
    projectId: 'cringe-bank',
    authDomain: 'cringe-bank.firebaseapp.com',
    storageBucket: 'cringe-bank.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvWjdZOZ2IQojrHKkexy6RDHzQVtuKB8I',
    appId: '1:688167942712:android:a6594e59ad424324a5c4cd',
    messagingSenderId: '688167942712',
    projectId: 'cringe-bank',
    storageBucket: 'cringe-bank.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApVdk8H0Ow6HbC_4WxKI5rO5L9wcsX8BM',
    appId: '1:688167942712:ios:59c7041cbfe447a1a5c4cd',
    messagingSenderId: '688167942712',
    projectId: 'cringe-bank',
    storageBucket: 'cringe-bank.firebasestorage.app',
    iosBundleId: 'com.example.cringeBankasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApVdk8H0Ow6HbC_4WxKI5rO5L9wcsX8BM',
    appId: '1:688167942712:ios:59c7041cbfe447a1a5c4cd',
    messagingSenderId: '688167942712',
    projectId: 'cringe-bank',
    storageBucket: 'cringe-bank.firebasestorage.app',
    iosBundleId: 'com.example.cringeBankasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLd4GiCnyk-1UfFF8hKUSc0prNQ5ERWoM',
    appId: '1:688167942712:web:480a21871f48adbea5c4cd',
    messagingSenderId: '688167942712',
    projectId: 'cringe-bank',
    authDomain: 'cringe-bank.firebaseapp.com',
    storageBucket: 'cringe-bank.firebasestorage.app',
  );

}